// Builds CSS variables, a flat JSON dump and typed JS exports from the token sources.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const src = (...parts) => path.join(root, 'src', ...parts);
const outDir = path.join(root, 'dist');

const PREFIX = 'mrd';

const coreFiles = [src('core', 'color.json'), src('core', 'base.json')];

// Which selector each theme hangs its variables on.
const themes = [
  { name: 'light', selector: ":root,\n[data-theme='light']" },
  { name: 'dark', selector: "[data-theme='dark']" },
  { name: 'high-contrast', selector: "[data-theme='high-contrast']" },
];

const kebab = (segments) =>
  segments
    .map((s) =>
      String(s)
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .toLowerCase(),
    )
    .join('-');

async function resolveTokens(extraSource) {
  const dictionary = new StyleDictionary({
    log: { verbosity: 'silent' },
    source: extraSource ? [...coreFiles, extraSource] : coreFiles,
    platforms: { css: { transformGroup: 'css' } },
  });
  const platformTokens = await dictionary.getPlatformTokens('css');
  return platformTokens.allTokens;
}

const valueOf = (token) => String(token.$value ?? token.value);

// Keep each list scoped to the file it was declared in.
const fromFile = (tokens, needle) => tokens.filter((t) => t.filePath.endsWith(needle));
const notFromFile = (tokens, needles) =>
  tokens.filter((t) => !needles.some((n) => t.filePath.endsWith(n)));

function toDeclarations(tokens) {
  const lines = [];
  for (const token of tokens) {
    if (token.path.join('.') === 'scheme') {
      lines.push(`  color-scheme: ${valueOf(token)};`);
    } else {
      lines.push(`  --${PREFIX}-${kebab(token.path)}: ${valueOf(token)};`);
    }
  }
  return lines.join('\n');
}

const themeFileNames = themes.map((t) => path.join('themes', `${t.name}.json`));

const cssBlocks = [];
const flat = { base: {}, themes: {} };

// Palette and non-colour tokens, shared by every theme.
const baseTokens = notFromFile(await resolveTokens(), themeFileNames);
cssBlocks.push(`:root {\n${toDeclarations(baseTokens)}\n}`);
for (const token of baseTokens) flat.base[kebab(token.path)] = valueOf(token);

for (const theme of themes) {
  const all = await resolveTokens(src('themes', `${theme.name}.json`));
  const own = fromFile(all, path.join('themes', `${theme.name}.json`));
  cssBlocks.push(`${theme.selector} {\n${toDeclarations(own)}\n}`);
  flat.themes[theme.name] = {};
  for (const token of own) flat.themes[theme.name][kebab(token.path)] = valueOf(token);
}

const names = Object.keys(flat.themes.light).filter((n) => n !== 'scheme');
const baseNames = Object.keys(flat.base);

const header = '/* Generated by scripts/build.mjs. Edit the JSON in src/, not this file. */\n';

const js = `${header}export const themes = ${JSON.stringify(themes.map((t) => t.name))};

export const cssVar = {
${[...baseNames, ...names].map((n) => `  '${n}': 'var(--${PREFIX}-${n})',`).join('\n')}
};
`;

const dts = `${header}export declare const themes: readonly ['light', 'dark', 'high-contrast'];
export type ThemeName = (typeof themes)[number];

export type TokenName =
${[...baseNames, ...names].map((n) => `  | '${n}'`).join('\n')};

export declare const cssVar: Readonly<Record<TokenName, string>>;
`;

await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, 'tokens.css'), `${header}${cssBlocks.join('\n\n')}\n`);
await writeFile(path.join(outDir, 'tokens.json'), `${JSON.stringify(flat, null, 2)}\n`);
await writeFile(path.join(outDir, 'tokens.js'), js);
await writeFile(path.join(outDir, 'tokens.d.ts'), dts);

console.log(
  `tokens: ${baseNames.length} shared, ${names.length} per theme, ${themes.length} themes`,
);
